### ISSUE TITLE
[Feature] Option to convert/rename .jfif to .jpg

### ISSUE THREAD

**Issue by Neatro** [Flkalas/TwitterMediaAssist#27]
Option to convert/rename .jfif to .jpg, as .jpg tends to be used more rather than .jfif

**Comment by Flkalas** [comment]
This issue is an old one. I've seen this problem several times, but all attempts to fix it have failed.

This problem combines two things.

Firstly, downloading extensions in the Chrome browser requires a very complex logic for renaming. If you use extensions without applying this logic or mix extensions with and without this logic, the names won't be changed correctly. Please refer to the following API documentation: https://developer.chrome.com/docs/extensions/reference/downloads/#event-onDeterminingFilename

Secondly, when downloading jpg images from the web on Windows, the default extension is set to jfif. This is a Windows problem and can be fixed by modifying the registry. You can resolve it by changing the Extension value from .jfif to .jpg for the key HKEY_CURRENT_USER\SOFTWARE\Classes\MIME\Database\Content Type\image/jpeg.

Both of these issues are not related to the TMA extension, and it is determined that TMA cannot control or fix them.
