### ISSUE TITLE
Image downloads fail when the original image is a PNG

### ISSUE THREAD

**Issue by Flyingtoast** [Flkalas/TwitterMediaAssist#35]
For additional context, I'm on Firefox. I don't know if the error really lies elsewhere, but all the files that would fail to download end with ".png?format=jpg&name=orig"

**Comment by Flkalas** [comment]
I am aware of this issue. However, it seems that Twitter's API has given up on providing the orignal version of png files.

The goal of the extension is to provide as much of the original upload by the artist or tweeter as possible. Therefore, I have to decide whether to provide the file as a modified, lower-resolution jpg, although it defeats the purpose a bit.

However, it is a worse experience if the feature does not work, so I will change it so that I can receive it as a jpg for now.

**Comment by Flkalas** [comment]
The issue has been resolved with https://github.com/Flkalas/TwitterMediaAssist/commit/e8c7a1102eeafcd5457de2bb4d1d9114daec3214
